use crate::kissing_component::kissing_component_bridge;
use crate::nodes::command_queue_node::CommandQueueNode;
use crate::nodes::tree_responder::TreeResponder;
use crate::prelude::*;
use crate::resources::entity_preregister::EntityPreregister;
use crate::resources::gd_tracker::AllNodes;

use std::collections::BTreeMap;

use bevy::prelude::*;
use godot::prelude::*;

// -----------------------
// * Conditional Imports *
// -----------------------

#[cfg(feature = "input")]
use crate::resources::input_event_argument::InputEventArgument;

#[cfg(feature = "input")]
use godot::classes::InputEvent;

// -------------------------
// * Top-Level Macro Calls *
// -------------------------

include!(concat!(env!("OUT_DIR"), "/add_components_for_node.rs"));

// -------------
// * Constants *
// -------------

pub(crate) const COMMAND_QUEUE_NODE_NAME: &str = "BevyKissingGodot_CommandQueueNode";

// --------------
// * KissingApp *
// --------------

/// Contains implementations for the "App" node generated by Bevy💋Godot.
///
/// Most of the code is kept here to prevent it from being implemented within a macro.
pub struct KissingApp {
	bevy_app: Option<App>,
	tree_responder: Option<Gd<TreeResponder>>,
	command_queue: Option<Gd<CommandQueueNode>>,
	node_id_to_bevy_entity: BTreeMap<InstanceId, Entity>,
}

impl Default for KissingApp {
	fn default() -> Self {
		Self {
			bevy_app: Some(bevy::prelude::App::new()),
			tree_responder: None,
			command_queue: None,
			node_id_to_bevy_entity: BTreeMap::new(),
		}
	}
}

/// `KissingApp` public responses.
///
/// This implementation contains all the functions that execute in response to Godot events.
impl KissingApp {
	/// Returns mutable reference to Bevy app instance.
	pub fn get_app_mut(&mut self) -> &mut App {
		self.bevy_app.as_mut().unwrap()
	}

	/// Sets the `app` to `None` to end any Bevy processing.
	pub fn clear_app(&mut self) {
		self.bevy_app = None;
	}

	/// Called immediately before the `#[kiss_bevy]` function implemented by the user.
	pub fn pre_ready(&mut self) {
		let Some(bevy_app) = self.bevy_app.as_mut() else {
			return;
		};
		bevy_app.add_plugins(crate::prelude::KissingCorePlugin);

		#[cfg(feature = "input")]
		bevy_app.add_plugins(crate::plugins::kissing_input_plugin::KissingInputPlugin);

		//self.bevy_app = bevy_app.into();
	}

	/// Called immediately after the `#[kiss_bevy]` function implemented by the user.
	pub fn post_ready(&mut self, app_node: Gd<Node>, tree: Gd<SceneTree>) {
		self.init_command_queue(app_node.clone());
		self.setup_scene_tree(tree.clone());
		self.init_tree_responder(app_node, tree.clone());

		if let Some(bevy_app) = self.bevy_app.as_mut() {
			bevy_app.insert_non_send_resource(tree);
			bevy_app.world_mut().run_schedule(bevy::prelude::Startup);
		}
	}

	/// Creates the callable that is invoked for all kissing events.
	///
	/// The [`app_node`] is bound as the last argument, and its [`Kisser::on_kissing_signal`]
	/// is called when the callable is called.
	fn init_command_queue(&mut self, mut app_node: Gd<Node>) {
		const CALLABLE_NAME: &str = "Bevy💋Godot signal_callable";

		// Call `on_kissing_signal` on the last argument passed to this callable.
		let callable = Callable::from_fn(CALLABLE_NAME, |args| {
			let Some(mut last) = args
				.last()
				.and_then(|v| v.try_to::<Gd<CommandQueueNode>>().ok())
			else {
				return;
			};
			last.bind_mut().on_kissing_signal(args);
		});

		// Create a command queue.
		let mut command_queue_node = CommandQueueNode::new_alloc();
		command_queue_node.set_name(COMMAND_QUEUE_NODE_NAME);
		app_node.call_deferred("add_child", vslice![command_queue_node]);

		// Store a reference to this node in scene tree for use in manual slot functions.
		if let Some(mut tree) = app_node.get_tree_or_null() {
			tree.set_meta(COMMAND_QUEUE_NODE_NAME, &command_queue_node.to_variant());
		}

		// Bind `command_queue_node` so it is always the last argument.
		let callable = callable.bind(vslice![command_queue_node]);
		command_queue_node.bind_mut().set_signal_callback(callable);
		self.command_queue = Some(command_queue_node);
	}

	/// Creates `TreeResponder` and connect it to the `SceneTree`'s signals.
	fn init_tree_responder(&mut self, mut app_node: Gd<Node>, tree: Gd<SceneTree>) {
		let mut tree_responder = TreeResponder::new_alloc();
		tree_responder.set_name("TreeResponder");
		app_node.call_deferred("add_child", vslice![tree_responder]);

		tree.signals()
			.node_added()
			.connect_other(&tree_responder, TreeResponder::on_node_added);
		tree.signals()
			.node_removed()
			.connect_other(&tree_responder, TreeResponder::on_node_removed);

		self.tree_responder = tree_responder.into();
	}

	/// Called every `_process` of the user's Bevy app node.
	pub fn process(&mut self, delta: f64) {
		let Some(bevy_app) = self.bevy_app.as_mut() else {
			return;
		};
		bevy_app.world_mut().resource_mut::<ProcessDelta>().0 = delta;
		bevy_app.world_mut().run_schedule(Process);
		bevy_app.world_mut().clear_trackers();
		self.handle_tree_responder_events();
		self.apply_command_queue();
	}

	/// Called every `_physics_process` of the user's Bevy app node.
	pub fn physics_process(&mut self, delta: f64) {
		let Some(bevy_app) = self.bevy_app.as_mut() else {
			return;
		};
		bevy_app.world_mut().resource_mut::<PhysicsProcessDelta>().0 = delta;
		bevy_app.world_mut().run_schedule(PhysicsProcess);
		self.handle_tree_responder_events();
		self.apply_command_queue();
	}

	/// Called every `_input` of the user's Bevy app node.
	#[cfg(feature = "input")]
	pub fn input(&mut self, event: Gd<InputEvent>) {
		let Some(bevy_app) = self.bevy_app.as_mut() else {
			return;
		};
		if let Some(mut arg) = bevy_app
			.world_mut()
			.get_non_send_resource_mut::<InputEventArgument>()
		{
			arg.0 = Some(event);
		}
		bevy_app.world_mut().run_schedule(GodotInput);
	}

	// /// Called for all editor-connected signals.
	// pub fn on_kissed_signal<T: KissingEvent>(&mut self, arguments: &[Variant]) {
	// 	let Some(bevy_app) = self.bevy_app.as_mut() else {
	// 		return;
	// 	};
	// 	let commands = bevy_app.world_mut().commands();
	// 	T::trigger(commands, arguments);
	// }

	/// Handle any changes that occured from `TreeResponder` receiving `SceneTree` events.
	fn handle_tree_responder_events(&mut self) {
		let Some(tree_responder) = self.tree_responder.as_mut() else {
			return;
		};
		let added_nodes = tree_responder.bind_mut().take_added_nodes();
		let removed_nodes = tree_responder.bind_mut().take_removed_nodes();
		for n in added_nodes {
			self.on_node_added(n);
		}
		for n in removed_nodes {
			self.on_node_removed(n);
		}
	}

	/// Execute the commands in the queue.
	fn apply_command_queue(&mut self) {
		let Some(bevy_app) = self.bevy_app.as_mut() else {
			return;
		};
		let Some(command_queue) = self.command_queue.as_mut() else {
			return;
		};

		let queue = command_queue.bind_mut().take_queue(); // Make sure `bind_mut` isn't active during apply.
		if let Some(mut queue) = queue {
			queue.apply(bevy_app.world_mut());
		}
	}

	/// Connected to `SceneTree`'s `node_added` signal.
	pub fn on_node_added(&mut self, mut node_added: Gd<Node>) {
		self.setup_node(&mut node_added);
	}

	/// Connected to `SceneTree`'s `node_removed` signal.
	pub fn on_node_removed(&mut self, node_removed: InstanceId) {
		let Some(bevy_app) = self.bevy_app.as_mut() else {
			return;
		};

		bevy_app
			.world_mut()
			.non_send_resource_mut::<AllNodes>()
			.remove(&node_removed);

		if let Some(entity) = self.node_id_to_bevy_entity.remove(&node_removed) {
			bevy_app.world_mut().despawn(entity);
		}
	}
}

/// `KissingApp` node set ups.
///
/// This implementation contains functions for initializing Godot nodes and stuff.
impl KissingApp {
	/// Called in the `_ready` for the App node to set up entities for all nodes.
	fn setup_scene_tree(&mut self, scene_tree: Gd<SceneTree>) {
		let Some(scene) = scene_tree.get_current_scene() else {
			godot_warn!(
				"Could not get [current_scene] when setting up [SceneTree] during make-out session between Bevy and Godot."
			);
			return;
		};

		self.setup_scene(scene);
	}

	/// Set up the scene.
	fn setup_scene(&mut self, mut scene: Gd<Node>) {
		self.setup_node_children(&mut scene);
	}

	/// Set up a node's children recusively.
	fn setup_node_children(&mut self, parent_node: &Gd<Node>) {
		for i in 0..parent_node.get_child_count() {
			let Some(mut child_node) = parent_node.get_child(i) else {
				continue;
			};

			self.setup_node(&mut child_node);
			self.setup_node_children(&child_node);
		}
	}

	/// Set up a node for the first time.
	fn setup_node(&mut self, node: &mut Gd<Node>) {
		let Some(world) = self.bevy_app.as_mut().map(|a| a.world_mut()) else {
			return;
		};

		let id = {
			let mut all_nodes = world.non_send_resource_mut::<AllNodes>();
			all_nodes.as_mut().register(node.clone())
		};

		let entity = {
			let mut entity_preregister = world.non_send_resource_mut::<EntityPreregister>();
			if let Some(entity) = entity_preregister.take_entity_if_exists(node) {
				world.entity_mut(entity)
			} else {
				world.spawn_empty()
			}
		};
		let mut entity = add_components_for_node(entity, node);

		entity.insert(id);
		let entity_id = entity.id();
		drop(entity); // Drop entity so world can be used in apply_kissing_components

		kissing_component_bridge::apply_kissing_components(node, world, entity_id);
		if let Some(command_queue) = self.command_queue.as_mut() {
			command_queue
				.bind_mut()
				.apply_kissing_events(node, entity_id);
		}

		if let Ok(mut ready_trait) = node.clone().try_dynify::<dyn BevyEntityReady>() {
			ready_trait
				.dyn_bind_mut()
				.bevy_entity_ready(world.entity_mut(entity_id));
		}

		self.node_id_to_bevy_entity
			.insert(node.instance_id(), entity_id);
	}
}
